### PR TITLE
Feature/us 83 architecture design

### PR DESCRIPTION
**Pull request by JCarlosHidalgoSosa**

### CODE REVIEW

**Review by daniel-espinoza-79 — APPROVED** [review]
It looks great to me

**Review by victor0villca — APPROVED** [review]
For my review, the generator of flight histories and the generator backbone classes and tests are implemented in the new architecture and working well. Also the connection between the gateway and user_database is good. Approved.

**Comment by zrock-dev** [comment]
Please re-branch from develop. Your current branch has old commits that have been rewritten.

**Comment by zrock-dev** [comment]
Hey, I'm getting this kind of errors with the binaries:

image

**Review by zrock-dev — COMMENTED** [review]
Looks good to me

**Review by zrock-dev — APPROVED** [review]

**Review by CatCoder36 — APPROVED** [review]
Good job

**Pull request merged**
