### PR TITLE
Feature/us 21 flight reservation

### PR DESCRIPTION
**Pull request by luiggymamani**
# Author: Luiggy Mamani Condori

## What?
Finish implementing the logic to book a flight.

## Why?
So that users can book a flight with a specific destination and priority.

## How?
Use the priority queue so that they are ordered in the flight by their ticket priority, also this data is stored in a local database.

### CODE REVIEW

**Review by JCarlosHidalgoSosa — COMMENTED** [review]
Please solve conflicts

**Review by JCarlosHidalgoSosa — APPROVED** [review]
good

**Comment by CatCoder36** [comment]
Please solve conflicts too

**Comment by zrock-dev** [comment]
This code is already in develop #42

**Comment by luiggymamani** [comment]
The changes from this branch were merged with the branch:
[https://github.com/zrock-dev/980/pull/42](url)

**Pull request closed without merging**
