### PR TITLE
Feature/us 151 user searc page UI

### PR DESCRIPTION
**Pull request by victor0villca**
## What?
I created the search users page ui and logic fetching communication with the backend

## How?
This was done with context react components, fetching api logic, and components rederization.

## Why?
To be able to  let the the user easily interact with the search page and search the users from the database.

#Author 
@victor0villca

### CODE REVIEW

**Review by zrock-dev — CHANGES_REQUESTED** [review]
Please update your changes with develop so that the queries can work.

**Comment by victor0villca** [comment]
> Please update your changes with develop so that the queries can work.

This issue has been solved.

**Comment by zrock-dev** [comment]
I tried a search with the letter "a" but there was no response.
[Uploading Screencast from 10-09-23 12:51:40.webm…]()

**Review by CatCoder36 — APPROVED** [review]

**Review by zrock-dev — APPROVED** [review]
Good job

**Pull request merged**
